### ISSUE TITLE
Fetching articles fails with error "invalid time value"

### ISSUE THREAD

**Issue by GuentherE** [hnykda/logseq-wallabag#1]
Hi,

Thanks for your efforts. I've compiled and installed it on a test version of wallabag running as a docker container.

It seems to connect to it and finds also the 7 test entries, but then fails at fetching them with the error message:"invalid time value".

Here is the console output of the dev tools (the content of the article was cut out to save some space here):

```
index-429a2cc3.js:235 Starting fetchArticles, settings state: {loading: false, inBackground: false, hasUrl: true, hasClientId: true, hasClientSecret: true, …}
index-429a2cc3.js:235 Setting loading state to true
index-429a2cc3.js:235 Creating Wallabag client and checking credentials
index.7a96a8a6.js:2 console.log event added
index-429a2cc3.js:235 Credentials valid, starting article fetch
index-429a2cc3.js:235 Fetching page 1
index-429a2cc3.js:214 getArticles called for page 1
index-429a2cc3.js:214 Fetching articles from: http://192.168.66.6:8066/api/entries.json?page=1&perPage=30
index.7a96a8a6.js:2 console.log event added
index-429a2cc3.js:214 Response data: {page: 1, pages: 1, total: 7, itemCount: 7}
index-429a2cc3.js:214 Sample article data: {
  "is_archived": 1,
  "is_starred": 0,
  "user_name": "wallabag",
  "user_email": "wallabag@wallabag.io",
  "user_id": 1,
  "tags": [
    {
      "id": 1,
      "label": "it",
      "slug": "t:it"
    }
  ],
  "is_public": false,
  "id": 10,
  "uid": null,
  "title": "docker volume create | Docker Docs",
  "url": "https://docs.docker.com/reference/cli/docker/volume/create/#driver-specific-options",
  "hashed_url": "c2471d33b6d221cd0e0e5dfa94733a5016d6795c",
  "origin_url": null,
  "given_url": "https://docs.docker.com/reference/cli/docker/volume/create/#driver-specific-options",
  "hashed_given_url": "c2471d33b6d221cd0e0e5dfa94733a5016d6795c",
  "archived_at": "2024-12-31T19:07:43+0000",
  "content": "... cut out ...",
  "created_at": "2024-12-30T20:13:14+0000",
  "updated_at": "2024-12-31T19:07:43+0000",
  "published_at": null,
  "published_by": [
    ""
  ],
  "starred_at": null,
  "annotations": [],
  "mimetype": null,
  "language": null,
  "reading_time": 2,
  "domain_name": "docs.docker.com",
  "preview_picture": null,
  "http_status": null,
  "headers": null,
  "_links": {
    "self": {
      "href": "/api/entries/10"
    }
  }
}
index-429a2cc3.js:235 Date format: {preferredDateFormat: 'yyyy-MM-dd', sampleArticleDate: '2024-12-30T20:13:14+0000', parsedDate: '2024-12-30T21:13:14.000+01:00', isValid: true, formattedDate: '2024-12-30'}
index-429a2cc3.js:235 Got page 1/1, items: 7
index-429a2cc3.js:238 Error in fetchArticles: RangeError: Invalid time value
    at wT (index-429a2cc3.js:203:24848)
    at Pa (index-429a2cc3.js:208:14392)
    at lf (index-429a2cc3.js:210:1708)
    at Pu (index-429a2cc3.js:235:1796)
    at async Object.syncWallabag (index-429a2cc3.js:241:263)
Pu @ index-429a2cc3.js:238
await in Pu (async)
syncWallabag @ index-429a2cc3.js:241
(anonymous) @ index-429a2cc3.js:12
index.7a96a8a6.js:2 console.log event added
index-429a2cc3.js:238 Resetting loading state in finally block
index-429a2cc3.js:214 resetLoadingState called
index-429a2cc3.js:214 Loading was true, setting to false
index.7a96a8a6.js:2 console.log event added
index.7a96a8a6.js:2 console.log event added
````

HTH Guenther

BTW: Happy New Year!

**Comment by GuentherE** [comment]
I played with the plugin a little bit more ...

For my tests I used the same settings as in my omnivore plugin:

```
{
  "generalSettings": "",
  "wallabagUrl": "http://192.168.66.6:8066",
  "clientId": "deleted",
  "clientSecret": "deleted",
  "userLogin": "wallabag",
  "userPassword": "wallabag",
  "filter": "import all my articles",
  "customQuery": "",
  "highlightOrder": "the time that highlights are updated",
  "isSinglePage": false,
  "createTemplate": "",
  "createTemplateDesc": "",
  "articleTemplate": "- [{{{title}}}]({{{url}}})\n      site:: [{{{siteName}}}]({{{url}}})\n      author:: {{{author}}}\n      date-saved:: [[{{{date}}}]]\n      id-wallabag:: {{{id}}}",
  "highlightTemplate": "> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #[[{{{name}}}]] {{/labels}}\n\n{{#note.length}}note:: {{{note}}}{{/note.length}}",
  "syncContent": false,
  "advancedSettings": "",
  "frequency": 60,
  "syncAt": "2025-01-01T17:45:24",
  "graph": "Wissensmanagement",
  "pageName": "{{{date}}}",
  "headingBlockTitle": "## 🔖 Articles",
  "disabled": false,
  "loading": false,
  "syncJobId": 22,
  "version": "1.16.5",
  "apiVersion": "\"2.6.10\"",
  "apiToken": "deleted",
  "refreshToken": "deleted",
  "expireDate": 1735753424206,
  "isTokenExpired": false
}
```

This led to the error in the first message above.

It is working partly when I select "Sync to a single page". So I guess the "save to individual pages" feature (in my case to the journal (setting page name: {{{date}}}) is at the moment not implemented.

The result when syncing to a single page is the same incomplete fetch as luca-git has reported.

**Comment by hnykda** [comment]
https://github.com/hnykda/wallabag-logseq-sync/issues/2#issuecomment-2568467410

**Comment by hnykda** [comment]
I believe this specific thing has been fixed.
